[package]
name = "klima-relay"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
klima-core = { path = "../klima-core" }
axum.workspace = true
tokio.workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time", "test-util"] }
